export const SERVER_URL =
  "https://getvideo.p.rapidapi.com/?url=https://www.youtube.com/watch?v=";

export const TRACK_REGX = '<a href="/watch\\?v=(.*?)"(.*?)title="(.*?)"';

export const PLAY_TRACK_REQUEST = "PLAY_TRACK_REQUEST";
export const PLAY_TRACK_SUCCESS = "PLAY_TRACK_SUCCESS";
export const PLAY_TRACK_ERROR = "PLAY_TRACK_ERROR";

export const ADD_TRACK_REQUEST = "ADD_TRACK_REQUEST";
export const ADD_TRACK_SUCCESS = "ADD_TRACK_SUCCESS";
export const ADD_TRACK_ERROR = "ADD_TRACK_ERROR";

export const GET_TRACKS_REQUEST = "GET_TRACKS_REQUEST";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_ERROR = "GET_TRACKS_ERROR";

export const GET_TRACK_REQUEST = "GET_TRACK_REQUEST";
export const GET_TRACK_SUCCESS = "GET_TRACK_SUCCESS";
export const GET_TRACK_ERROR = "GET_TRACK_ERROR";

export const GET_PLAYLISTS_REQUEST = "GET_PLAYLISTS_REQUEST";
export const GET_PLAYLISTS_SUCCESS = "GET_PLAYLISTS_SUCCESS";
export const GET_PLAYLISTS_ERROR = "GET_PLAYLISTS_ERROR";

export const ADD_TRACK_TO_PLAYLIST_REQUEST = "ADD_TRACK_TO_PLAYLIST_REQUEST";
export const ADD_TRACK_TO_PLAYLIST_SUCCESS = "ADD_TRACK_TO_PLAYLIST_SUCCESS";
export const ADD_TRACK_TO_PLAYLIST_ERROR = "ADD_TRACK_TO_PLAYLIST_ERROR";

export const REMOVE_TRACK_FROM_PLAYLIST_REQUEST =
  "REMOVE_TRACK_FROM_PLAYLIST_REQUEST";
export const REMOVE_TRACK_FROM_PLAYLIST_SUCCESS =
  "REMOVE_TRACK_FROM_PLAYLIST_SUCCESS";
export const REMOVE_TRACK_FROM_PLAYLIST_ERROR =
  "REMOVE_TRACK_FROM_PLAYLIST_ERROR";

export const SET_PLAYLIST = "SET_PLAYLIST";
export const SET_PLAYING = "SET_PLAYING";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";

export const PLAY_PLAYLIST_REQUEST = "PLAY_PLAYLIST_REQUEST";
export const PLAY_PLAYLIST_SUCCESS = "PLAY_PLAYLIST_SUCCESS";
export const PLAY_PLAYLIST_ERROR = "PLAY_PLAYLIST_ERROR";
